// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: rag_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status enum for document processing results
type DocumentProcessingStatus int32

const (
	DocumentProcessingStatus_DOCUMENT_STATUS_UNSPECIFIED DocumentProcessingStatus = 0
	DocumentProcessingStatus_DOCUMENT_STATUS_PROCESSING  DocumentProcessingStatus = 1
	DocumentProcessingStatus_DOCUMENT_STATUS_COMPLETED   DocumentProcessingStatus = 2
	DocumentProcessingStatus_DOCUMENT_STATUS_ERROR       DocumentProcessingStatus = 3
)

// Enum value maps for DocumentProcessingStatus.
var (
	DocumentProcessingStatus_name = map[int32]string{
		0: "DOCUMENT_STATUS_UNSPECIFIED",
		1: "DOCUMENT_STATUS_PROCESSING",
		2: "DOCUMENT_STATUS_COMPLETED",
		3: "DOCUMENT_STATUS_ERROR",
	}
	DocumentProcessingStatus_value = map[string]int32{
		"DOCUMENT_STATUS_UNSPECIFIED": 0,
		"DOCUMENT_STATUS_PROCESSING":  1,
		"DOCUMENT_STATUS_COMPLETED":   2,
		"DOCUMENT_STATUS_ERROR":       3,
	}
)

func (x DocumentProcessingStatus) Enum() *DocumentProcessingStatus {
	p := new(DocumentProcessingStatus)
	*p = x
	return p
}

func (x DocumentProcessingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentProcessingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rag_service_proto_enumTypes[0].Descriptor()
}

func (DocumentProcessingStatus) Type() protoreflect.EnumType {
	return &file_rag_service_proto_enumTypes[0]
}

func (x DocumentProcessingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentProcessingStatus.Descriptor instead.
func (DocumentProcessingStatus) EnumDescriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{0}
}

// --------------------------------------------------------
// Request Message Definitions
// --------------------------------------------------------
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                          // User's question
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Unique session identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_rag_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// --------------------------------------------------------
// Response Message Definitions
// --------------------------------------------------------
type ChatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Answer           string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`                                                 // Generated answer
	SourceDocuments  []*Source              `protobuf:"bytes,2,rep,name=source_documents,json=sourceDocuments,proto3" json:"source_documents,omitempty"`        // Retrieved source documents
	ProcessingTimeMs float64                `protobuf:"fixed64,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"` // Processing time in milliseconds
	IsCached         bool                   `protobuf:"varint,4,opt,name=is_cached,json=isCached,proto3" json:"is_cached,omitempty"`                            // Whether the response was served from semantic cache
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_rag_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *ChatResponse) GetSourceDocuments() []*Source {
	if x != nil {
		return x.SourceDocuments
	}
	return nil
}

func (x *ChatResponse) GetProcessingTimeMs() float64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *ChatResponse) GetIsCached() bool {
	if x != nil {
		return x.IsCached
	}
	return false
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`  // Unique identifier for the source document
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                        // Name of the source document
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"` // Page number in the document
	Snippet       string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`                          // Relevant text snippet
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`                            // Relevance score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_rag_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{2}
}

func (x *Source) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Source) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Source) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *Source) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Source) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// --------------------------------------------------------
// Process Document Message Definitions (Go -> Python)
// --------------------------------------------------------
type ProcessDocumentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DocumentId     string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`              // UUID assigned by Go (source of truth)
	FilePath       string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                    // Path to the file on disk
	Filename       string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`                                    // Original filename
	ContentType    string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`           // MIME type of the file
	OrganizationId uint32                 `protobuf:"varint,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // Organization ID for multi-tenancy
	GroupId        uint32                 `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                      // Group ID (0 if org-wide)
	OwnerId        uint32                 `protobuf:"varint,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                      // Owner user ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessDocumentRequest) Reset() {
	*x = ProcessDocumentRequest{}
	mi := &file_rag_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentRequest) ProtoMessage() {}

func (x *ProcessDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentRequest.ProtoReflect.Descriptor instead.
func (*ProcessDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ProcessDocumentRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ProcessDocumentRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ProcessDocumentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ProcessDocumentRequest) GetOrganizationId() uint32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *ProcessDocumentRequest) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ProcessDocumentRequest) GetOwnerId() uint32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type ProcessDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`     // Echo back the document ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                               // "success", "error"
	ChunksCount   int32                  `protobuf:"varint,3,opt,name=chunks_count,json=chunksCount,proto3" json:"chunks_count,omitempty"` // Number of chunks created
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                             // Additional info or error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDocumentResponse) Reset() {
	*x = ProcessDocumentResponse{}
	mi := &file_rag_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentResponse) ProtoMessage() {}

func (x *ProcessDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentResponse.ProtoReflect.Descriptor instead.
func (*ProcessDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ProcessDocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessDocumentResponse) GetChunksCount() int32 {
	if x != nil {
		return x.ChunksCount
	}
	return 0
}

func (x *ProcessDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --------------------------------------------------------
// Delete Document Message Definitions
// --------------------------------------------------------
type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"` // Unique identifier for the document to be deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_rag_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // Status message
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Additional information or error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_rag_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DocumentStatusRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	DocumentId    string                   `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`          // UUID of the document
	Status        DocumentProcessingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=rag.DocumentProcessingStatus" json:"status,omitempty"` // COMPLETED or ERROR
	ChunksCount   int32                    `protobuf:"varint,3,opt,name=chunks_count,json=chunksCount,proto3" json:"chunks_count,omitempty"`      // Number of chunks (for COMPLETED)
	ErrorMessage  string                   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`    // Error message (for ERROR status)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentStatusRequest) Reset() {
	*x = DocumentStatusRequest{}
	mi := &file_rag_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentStatusRequest) ProtoMessage() {}

func (x *DocumentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentStatusRequest.ProtoReflect.Descriptor instead.
func (*DocumentStatusRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{7}
}

func (x *DocumentStatusRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentStatusRequest) GetStatus() DocumentProcessingStatus {
	if x != nil {
		return x.Status
	}
	return DocumentProcessingStatus_DOCUMENT_STATUS_UNSPECIFIED
}

func (x *DocumentStatusRequest) GetChunksCount() int32 {
	if x != nil {
		return x.ChunksCount
	}
	return 0
}

func (x *DocumentStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DocumentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether the update was successful
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Additional information or error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentStatusResponse) Reset() {
	*x = DocumentStatusResponse{}
	mi := &file_rag_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentStatusResponse) ProtoMessage() {}

func (x *DocumentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentStatusResponse.ProtoReflect.Descriptor instead.
func (*DocumentStatusResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{8}
}

func (x *DocumentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DocumentStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rag_service_proto protoreflect.FileDescriptor

const file_rag_service_proto_rawDesc = "" +
	"\n" +
	"\x11rag_service.proto\x12\x03rag\"B\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xa9\x01\n" +
	"\fChatResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x126\n" +
	"\x10source_documents\x18\x02 \x03(\v2\v.rag.SourceR\x0fsourceDocuments\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x01R\x10processingTimeMs\x12\x1b\n" +
	"\tis_cached\x18\x04 \x01(\bR\bisCached\"\x96\x01\n" +
	"\x06Source\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\"\xf4\x01\n" +
	"\x16ProcessDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\rR\x0eorganizationId\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\rR\agroupId\x12\x19\n" +
	"\bowner_id\x18\a \x01(\rR\aownerId\"\x8f\x01\n" +
	"\x17ProcessDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fchunks_count\x18\x03 \x01(\x05R\vchunksCount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"8\n" +
	"\x15DeleteDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"J\n" +
	"\x16DeleteDocumentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb7\x01\n" +
	"\x15DocumentStatusRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.rag.DocumentProcessingStatusR\x06status\x12!\n" +
	"\fchunks_count\x18\x03 \x01(\x05R\vchunksCount\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"L\n" +
	"\x16DocumentStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x95\x01\n" +
	"\x18DocumentProcessingStatus\x12\x1f\n" +
	"\x1bDOCUMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDOCUMENT_STATUS_PROCESSING\x10\x01\x12\x1d\n" +
	"\x19DOCUMENT_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15DOCUMENT_STATUS_ERROR\x10\x032<\n" +
	"\vChatService\x12-\n" +
	"\x04Chat\x12\x10.rag.ChatRequest\x1a\x11.rag.ChatResponse0\x012\xaf\x01\n" +
	"\x14KnowledgeBaseService\x12L\n" +
	"\x0fProcessDocument\x12\x1b.rag.ProcessDocumentRequest\x1a\x1c.rag.ProcessDocumentResponse\x12I\n" +
	"\x0eDeleteDocument\x12\x1a.rag.DeleteDocumentRequest\x1a\x1b.rag.DeleteDocumentResponse2]\n" +
	"\n" +
	"RagService\x12O\n" +
	"\x14UpdateDocumentStatus\x12\x1a.rag.DocumentStatusRequest\x1a\x1b.rag.DocumentStatusResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_rag_service_proto_rawDescOnce sync.Once
	file_rag_service_proto_rawDescData []byte
)

func file_rag_service_proto_rawDescGZIP() []byte {
	file_rag_service_proto_rawDescOnce.Do(func() {
		file_rag_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)))
	})
	return file_rag_service_proto_rawDescData
}

var file_rag_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rag_service_proto_goTypes = []any{
	(DocumentProcessingStatus)(0),   // 0: rag.DocumentProcessingStatus
	(*ChatRequest)(nil),             // 1: rag.ChatRequest
	(*ChatResponse)(nil),            // 2: rag.ChatResponse
	(*Source)(nil),                  // 3: rag.Source
	(*ProcessDocumentRequest)(nil),  // 4: rag.ProcessDocumentRequest
	(*ProcessDocumentResponse)(nil), // 5: rag.ProcessDocumentResponse
	(*DeleteDocumentRequest)(nil),   // 6: rag.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),  // 7: rag.DeleteDocumentResponse
	(*DocumentStatusRequest)(nil),   // 8: rag.DocumentStatusRequest
	(*DocumentStatusResponse)(nil),  // 9: rag.DocumentStatusResponse
}
var file_rag_service_proto_depIdxs = []int32{
	3, // 0: rag.ChatResponse.source_documents:type_name -> rag.Source
	0, // 1: rag.DocumentStatusRequest.status:type_name -> rag.DocumentProcessingStatus
	1, // 2: rag.ChatService.Chat:input_type -> rag.ChatRequest
	4, // 3: rag.KnowledgeBaseService.ProcessDocument:input_type -> rag.ProcessDocumentRequest
	6, // 4: rag.KnowledgeBaseService.DeleteDocument:input_type -> rag.DeleteDocumentRequest
	8, // 5: rag.RagService.UpdateDocumentStatus:input_type -> rag.DocumentStatusRequest
	2, // 6: rag.ChatService.Chat:output_type -> rag.ChatResponse
	5, // 7: rag.KnowledgeBaseService.ProcessDocument:output_type -> rag.ProcessDocumentResponse
	7, // 8: rag.KnowledgeBaseService.DeleteDocument:output_type -> rag.DeleteDocumentResponse
	9, // 9: rag.RagService.UpdateDocumentStatus:output_type -> rag.DocumentStatusResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rag_service_proto_init() }
func file_rag_service_proto_init() {
	if File_rag_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_rag_service_proto_goTypes,
		DependencyIndexes: file_rag_service_proto_depIdxs,
		EnumInfos:         file_rag_service_proto_enumTypes,
		MessageInfos:      file_rag_service_proto_msgTypes,
	}.Build()
	File_rag_service_proto = out.File
	file_rag_service_proto_goTypes = nil
	file_rag_service_proto_depIdxs = nil
}
