import asyncio
from typing import List

from config import Settings
from fastembed import TextEmbedding
from logger import AppLogger


class EmbeddingGenerator:
    """
    A class to generate text embeddings using a specified embedding model.

    Attributes:
        logger (Logger): Logger instance for logging messages.
        model (TextEmbedding): The text embedding model used for generating embeddings.
        _vector_size (int): The size of the embedding vectors.

    Methods:
        vector_size:
            Returns the size of the embedding vectors.

        generate_sync(documents: List[str]) -> List[List[float]]:
            Generates embeddings synchronously for a list of documents.

        generate(documents: List[str]) -> List[List[float]]:
            Asynchronously generates embeddings for a list of documents.
    """

    def __init__(self, settings: Settings, logger: AppLogger) -> None:
        """
        Initializes the EmbeddingGenerator with the specified settings and logger.

        Args:
            settings (Settings): Configuration settings containing the embedding model name.
            logger (AppLogger): Application logger instance for logging messages.

        Attributes:
            logger (Logger): Logger instance for the current module.
            model (TextEmbedding): Instance of the TextEmbedding model initialized with the specified model name.
            _vector_size (int): Size of the embedding vectors generated by the model.

        Logs:
            - Information about the model being loaded.
            - Confirmation of the model's successful loading and its vector size.
        """

        self.logger = logger.get_logger(__name__)

        self.logger.info(f"📦 [EmbeddingGenerator] Loading model: {settings.embedding_model_name}")
        self.model = TextEmbedding(
            model_name=settings.embedding_model_name, cache_dir="/home/appuser/.cache/models"
        )

        dummy_vec = list(self.model.embed(["test"]))[0]
        self._vector_size = len(dummy_vec)
        self.logger.info(
            f"✅ [EmbeddingGenerator] Model loaded with vector size: {self._vector_size}"
        )

    @property
    def vector_size(self) -> int:
        """Returns the size of the embedding vectors."""
        return self._vector_size

    def generate_sync(self, documents: List[str]) -> List[List[float]]:
        """
        Generate embeddings synchronously for a list of input documents.

        This method takes a list of documents (strings) and generates their
        corresponding embeddings using the model. The embeddings are returned
        as a list of lists of floats.

        Args:
            documents (List[str]): A list of input documents for which embeddings
                need to be generated.

        Returns:
            List[List[float]]: A list of embeddings, where each embedding is
            represented as a list of floats.

        Logs:
            Logs the number of documents being processed for embedding generation.
        """

        self.logger.info(
            f"🔍 [EmbeddingGenerator] Generating embeddings for {len(documents)} documents (sync)"
        )
        return [e.tolist() for e in self.model.embed(documents)]

    async def generate(self, documents: List[str]) -> List[List[float]]:
        """
        Asynchronously generates embeddings for a list of documents.

        Args:
            documents (List[str]): A list of input documents as strings.

        Returns:
            List[List[float]]: A list of embeddings, where each embedding is represented
            as a list of floating-point numbers.
        """

        return await asyncio.to_thread(self.generate_sync, documents)
