"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ChatRequest(google.protobuf.message.Message):
    """--------------------------------------------------------
    Request Message Definitions
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUERY_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    query: builtins.str
    """User's question"""
    session_id: builtins.str
    """Unique session identifier"""
    def __init__(
        self,
        *,
        query: builtins.str = ...,
        session_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["query", b"query", "session_id", b"session_id"]) -> None: ...

Global___ChatRequest: typing_extensions.TypeAlias = ChatRequest

@typing.final
class ChatResponse(google.protobuf.message.Message):
    """--------------------------------------------------------
    Response Message Definitions
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANSWER_FIELD_NUMBER: builtins.int
    SOURCE_DOCUMENTS_FIELD_NUMBER: builtins.int
    PROCESSING_TIME_MS_FIELD_NUMBER: builtins.int
    answer: builtins.str
    """Generated answer"""
    processing_time_ms: builtins.float
    """Processing time in milliseconds"""
    @property
    def source_documents(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Source]:
        """Retrieved source documents"""

    def __init__(
        self,
        *,
        answer: builtins.str = ...,
        source_documents: collections.abc.Iterable[Global___Source] | None = ...,
        processing_time_ms: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["answer", b"answer", "processing_time_ms", b"processing_time_ms", "source_documents", b"source_documents"]) -> None: ...

Global___ChatResponse: typing_extensions.TypeAlias = ChatResponse

@typing.final
class Source(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCUMENT_ID_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    PAGE_NUMBER_FIELD_NUMBER: builtins.int
    SNIPPET_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    document_id: builtins.str
    """Unique identifier for the source document"""
    filename: builtins.str
    """Name of the source document"""
    page_number: builtins.int
    """Page number in the document"""
    snippet: builtins.str
    """Relevant text snippet"""
    score: builtins.float
    """Relevance score"""
    def __init__(
        self,
        *,
        document_id: builtins.str = ...,
        filename: builtins.str = ...,
        page_number: builtins.int = ...,
        snippet: builtins.str = ...,
        score: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["document_id", b"document_id", "filename", b"filename", "page_number", b"page_number", "score", b"score", "snippet", b"snippet"]) -> None: ...

Global___Source: typing_extensions.TypeAlias = Source

@typing.final
class ProcessDocumentRequest(google.protobuf.message.Message):
    """--------------------------------------------------------
    Process Document Message Definitions (Go -> Python)
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCUMENT_ID_FIELD_NUMBER: builtins.int
    FILE_PATH_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    GROUP_ID_FIELD_NUMBER: builtins.int
    OWNER_ID_FIELD_NUMBER: builtins.int
    document_id: builtins.str
    """UUID assigned by Go (source of truth)"""
    file_path: builtins.str
    """Path to the file on disk"""
    filename: builtins.str
    """Original filename"""
    content_type: builtins.str
    """MIME type of the file"""
    organization_id: builtins.int
    """Organization ID for multi-tenancy"""
    group_id: builtins.int
    """Group ID (0 if org-wide)"""
    owner_id: builtins.int
    """Owner user ID"""
    def __init__(
        self,
        *,
        document_id: builtins.str = ...,
        file_path: builtins.str = ...,
        filename: builtins.str = ...,
        content_type: builtins.str = ...,
        organization_id: builtins.int = ...,
        group_id: builtins.int = ...,
        owner_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content_type", b"content_type", "document_id", b"document_id", "file_path", b"file_path", "filename", b"filename", "group_id", b"group_id", "organization_id", b"organization_id", "owner_id", b"owner_id"]) -> None: ...

Global___ProcessDocumentRequest: typing_extensions.TypeAlias = ProcessDocumentRequest

@typing.final
class ProcessDocumentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCUMENT_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CHUNKS_COUNT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    document_id: builtins.str
    """Echo back the document ID"""
    status: builtins.str
    """"success", "error" """
    chunks_count: builtins.int
    """Number of chunks created"""
    message: builtins.str
    """Additional info or error message"""
    def __init__(
        self,
        *,
        document_id: builtins.str = ...,
        status: builtins.str = ...,
        chunks_count: builtins.int = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chunks_count", b"chunks_count", "document_id", b"document_id", "message", b"message", "status", b"status"]) -> None: ...

Global___ProcessDocumentResponse: typing_extensions.TypeAlias = ProcessDocumentResponse

@typing.final
class DeleteDocumentRequest(google.protobuf.message.Message):
    """--------------------------------------------------------
    Delete Document Message Definitions
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCUMENT_ID_FIELD_NUMBER: builtins.int
    document_id: builtins.str
    """Unique identifier for the document to be deleted"""
    def __init__(
        self,
        *,
        document_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["document_id", b"document_id"]) -> None: ...

Global___DeleteDocumentRequest: typing_extensions.TypeAlias = DeleteDocumentRequest

@typing.final
class DeleteDocumentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: builtins.str
    """Status message"""
    message: builtins.str
    """Additional information or error message"""
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "status", b"status"]) -> None: ...

Global___DeleteDocumentResponse: typing_extensions.TypeAlias = DeleteDocumentResponse
