"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ChatRequest(google.protobuf.message.Message):
    """--------------------------------------------------------
    Request Message Definitions
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUERY_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    query: builtins.str
    """User's question"""
    session_id: builtins.str
    """Unique session identifier"""
    @property
    def config(self) -> Global___QueryConfig:
        """Retrieval configuration"""

    def __init__(
        self,
        *,
        query: builtins.str = ...,
        session_id: builtins.str = ...,
        config: Global___QueryConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "query", b"query", "session_id", b"session_id"]) -> None: ...

Global___ChatRequest: typing_extensions.TypeAlias = ChatRequest

@typing.final
class QueryConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLECTION_NAME_FIELD_NUMBER: builtins.int
    MAX_RESULTS_FIELD_NUMBER: builtins.int
    collection_name: builtins.str
    """Name of the document collection"""
    max_results: builtins.int
    """Maximum number of source documents to retrieve"""
    def __init__(
        self,
        *,
        collection_name: builtins.str = ...,
        max_results: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collection_name", b"collection_name", "max_results", b"max_results"]) -> None: ...

Global___QueryConfig: typing_extensions.TypeAlias = QueryConfig

@typing.final
class ChatResponse(google.protobuf.message.Message):
    """--------------------------------------------------------
    Response Message Definitions
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANSWER_FIELD_NUMBER: builtins.int
    SOURCE_DOCUMENTS_FIELD_NUMBER: builtins.int
    PROCESSING_TIME_MS_FIELD_NUMBER: builtins.int
    answer: builtins.str
    """Generated answer"""
    processing_time_ms: builtins.float
    """Processing time in milliseconds"""
    @property
    def source_documents(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Source]:
        """Retrieved source documents"""

    def __init__(
        self,
        *,
        answer: builtins.str = ...,
        source_documents: collections.abc.Iterable[Global___Source] | None = ...,
        processing_time_ms: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["answer", b"answer", "processing_time_ms", b"processing_time_ms", "source_documents", b"source_documents"]) -> None: ...

Global___ChatResponse: typing_extensions.TypeAlias = ChatResponse

@typing.final
class Source(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILENAME_FIELD_NUMBER: builtins.int
    PAGE_NUMBER_FIELD_NUMBER: builtins.int
    SNIPPET_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    filename: builtins.str
    """Name of the source document"""
    page_number: builtins.int
    """Page number in the document"""
    snippet: builtins.str
    """Relevant text snippet"""
    score: builtins.float
    """Relevance score"""
    def __init__(
        self,
        *,
        filename: builtins.str = ...,
        page_number: builtins.int = ...,
        snippet: builtins.str = ...,
        score: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filename", b"filename", "page_number", b"page_number", "score", b"score", "snippet", b"snippet"]) -> None: ...

Global___Source: typing_extensions.TypeAlias = Source

@typing.final
class UploadRequest(google.protobuf.message.Message):
    """--------------------------------------------------------
    Upload Message Definitions
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILENAME_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    FILE_CONTENT_FIELD_NUMBER: builtins.int
    filename: builtins.str
    """Name of the file being uploaded"""
    content_type: builtins.str
    """MIME type of the file (e.g., application/pdf)"""
    file_content: builtins.bytes
    """Binary content of the file"""
    def __init__(
        self,
        *,
        filename: builtins.str = ...,
        content_type: builtins.str = ...,
        file_content: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content_type", b"content_type", "file_content", b"file_content", "filename", b"filename"]) -> None: ...

Global___UploadRequest: typing_extensions.TypeAlias = UploadRequest

@typing.final
class UploadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    CHUNKS_COUNT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: builtins.str
    """Status message"""
    chunks_count: builtins.int
    """Number of chunks created from the file"""
    message: builtins.str
    """Additional information or error message"""
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        chunks_count: builtins.int = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chunks_count", b"chunks_count", "message", b"message", "status", b"status"]) -> None: ...

Global___UploadResponse: typing_extensions.TypeAlias = UploadResponse
