# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import grpc.experimental

from pb import rag_service_pb2 as rag__service__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in rag_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ChatServiceStub(object):
    """--------------------------------------------------------
    Chat Service Definition
    --------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
            "/rag.ChatService/Chat",
            request_serializer=rag__service__pb2.ChatRequest.SerializeToString,
            response_deserializer=rag__service__pb2.ChatResponse.FromString,
            _registered_method=True,
        )


class ChatServiceServicer(object):
    """--------------------------------------------------------
    Chat Service Definition
    --------------------------------------------------------
    """

    def Chat(self, request, context):
        """/ Chat is an RPC that processes a user's query and returns a response.
        / It takes a ChatRequest containing the query, session ID, and configuration,
        / and returns a ChatResponse with the generated answer and source documents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Chat": grpc.unary_stream_rpc_method_handler(
            servicer.Chat,
            request_deserializer=rag__service__pb2.ChatRequest.FromString,
            response_serializer=rag__service__pb2.ChatResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("rag.ChatService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rag.ChatService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """--------------------------------------------------------
    Chat Service Definition
    --------------------------------------------------------
    """

    @staticmethod
    def Chat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/rag.ChatService/Chat",
            rag__service__pb2.ChatRequest.SerializeToString,
            rag__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class KnowledgeBaseServiceStub(object):
    """--------------------------------------------------------
    Knowledge Base Service Definition
    --------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
            "/rag.KnowledgeBaseService/ProcessDocument",
            request_serializer=rag__service__pb2.ProcessDocumentRequest.SerializeToString,
            response_deserializer=rag__service__pb2.ProcessDocumentResponse.FromString,
            _registered_method=True,
        )
        self.DeleteDocument = channel.unary_unary(
            "/rag.KnowledgeBaseService/DeleteDocument",
            request_serializer=rag__service__pb2.DeleteDocumentRequest.SerializeToString,
            response_deserializer=rag__service__pb2.DeleteDocumentResponse.FromString,
            _registered_method=True,
        )


class KnowledgeBaseServiceServicer(object):
    """--------------------------------------------------------
    Knowledge Base Service Definition
    --------------------------------------------------------
    """

    def ProcessDocument(self, request, context):
        """/ ProcessDocument is an RPC that processes a document that was already saved by Go.
        / Go provides the document_id, file_path, and metadata. Python processes and indexes it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteDocument(self, request, context):
        """/ DeleteDocument is an RPC that deletes a specified document from the vector store.
        / It takes a DeleteDocumentRequest and returns a DeleteDocumentResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_KnowledgeBaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ProcessDocument": grpc.unary_unary_rpc_method_handler(
            servicer.ProcessDocument,
            request_deserializer=rag__service__pb2.ProcessDocumentRequest.FromString,
            response_serializer=rag__service__pb2.ProcessDocumentResponse.SerializeToString,
        ),
        "DeleteDocument": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteDocument,
            request_deserializer=rag__service__pb2.DeleteDocumentRequest.FromString,
            response_serializer=rag__service__pb2.DeleteDocumentResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "rag.KnowledgeBaseService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rag.KnowledgeBaseService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class KnowledgeBaseService(object):
    """--------------------------------------------------------
    Knowledge Base Service Definition
    --------------------------------------------------------
    """

    @staticmethod
    def ProcessDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rag.KnowledgeBaseService/ProcessDocument",
            rag__service__pb2.ProcessDocumentRequest.SerializeToString,
            rag__service__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rag.KnowledgeBaseService/DeleteDocument",
            rag__service__pb2.DeleteDocumentRequest.SerializeToString,
            rag__service__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
