"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ChatRequest(google.protobuf.message.Message):
    """--------------------------------------------------------
    Request Message Definitions
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUERY_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    query: builtins.str
    """User's question"""
    session_id: builtins.str
    """Unique session identifier"""
    def __init__(
        self,
        *,
        query: builtins.str = ...,
        session_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["query", b"query", "session_id", b"session_id"]) -> None: ...

Global___ChatRequest: typing_extensions.TypeAlias = ChatRequest

@typing.final
class ChatResponse(google.protobuf.message.Message):
    """--------------------------------------------------------
    Response Message Definitions
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANSWER_FIELD_NUMBER: builtins.int
    SOURCE_DOCUMENTS_FIELD_NUMBER: builtins.int
    PROCESSING_TIME_MS_FIELD_NUMBER: builtins.int
    answer: builtins.str
    """Generated answer"""
    processing_time_ms: builtins.float
    """Processing time in milliseconds"""
    @property
    def source_documents(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Source]:
        """Retrieved source documents"""

    def __init__(
        self,
        *,
        answer: builtins.str = ...,
        source_documents: collections.abc.Iterable[Global___Source] | None = ...,
        processing_time_ms: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["answer", b"answer", "processing_time_ms", b"processing_time_ms", "source_documents", b"source_documents"]) -> None: ...

Global___ChatResponse: typing_extensions.TypeAlias = ChatResponse

@typing.final
class Source(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCUMENT_ID_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    PAGE_NUMBER_FIELD_NUMBER: builtins.int
    SNIPPET_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    document_id: builtins.str
    """Unique identifier for the source document"""
    filename: builtins.str
    """Name of the source document"""
    page_number: builtins.int
    """Page number in the document"""
    snippet: builtins.str
    """Relevant text snippet"""
    score: builtins.float
    """Relevance score"""
    def __init__(
        self,
        *,
        document_id: builtins.str = ...,
        filename: builtins.str = ...,
        page_number: builtins.int = ...,
        snippet: builtins.str = ...,
        score: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["document_id", b"document_id", "filename", b"filename", "page_number", b"page_number", "score", b"score", "snippet", b"snippet"]) -> None: ...

Global___Source: typing_extensions.TypeAlias = Source

@typing.final
class UploadRequest(google.protobuf.message.Message):
    """--------------------------------------------------------
    Upload Message Definitions
    --------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FIELD_NUMBER: builtins.int
    CHUNK_FIELD_NUMBER: builtins.int
    chunk: builtins.bytes
    """Chunk of file data"""
    @property
    def metadata(self) -> Global___UploadMetadata:
        """Metadata about the file"""

    def __init__(
        self,
        *,
        metadata: Global___UploadMetadata | None = ...,
        chunk: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["chunk", b"chunk", "data", b"data", "metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["chunk", b"chunk", "data", b"data", "metadata", b"metadata"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["data", b"data"]) -> typing.Literal["metadata", "chunk"] | None: ...

Global___UploadRequest: typing_extensions.TypeAlias = UploadRequest

@typing.final
class UploadMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILENAME_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    filename: builtins.str
    """Name of the file"""
    content_type: builtins.str
    """MIME type of the file (e.g., application/pdf)"""
    def __init__(
        self,
        *,
        filename: builtins.str = ...,
        content_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content_type", b"content_type", "filename", b"filename"]) -> None: ...

Global___UploadMetadata: typing_extensions.TypeAlias = UploadMetadata

@typing.final
class UploadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCUMENT_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CHUNKS_COUNT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    document_id: builtins.str
    """Unique identifier for the uploaded document"""
    status: builtins.str
    """Status message"""
    chunks_count: builtins.int
    """Number of chunks created from the file"""
    message: builtins.str
    """Additional information or error message"""
    def __init__(
        self,
        *,
        document_id: builtins.str = ...,
        status: builtins.str = ...,
        chunks_count: builtins.int = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chunks_count", b"chunks_count", "document_id", b"document_id", "message", b"message", "status", b"status"]) -> None: ...

Global___UploadResponse: typing_extensions.TypeAlias = UploadResponse

@typing.final
class DeleteDocumentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCUMENT_ID_FIELD_NUMBER: builtins.int
    document_id: builtins.str
    """Unique identifier for the document to be deleted"""
    def __init__(
        self,
        *,
        document_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["document_id", b"document_id"]) -> None: ...

Global___DeleteDocumentRequest: typing_extensions.TypeAlias = DeleteDocumentRequest

@typing.final
class DeleteDocumentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: builtins.str
    """Status message"""
    message: builtins.str
    """Additional information or error message"""
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "status", b"status"]) -> None: ...

Global___DeleteDocumentResponse: typing_extensions.TypeAlias = DeleteDocumentResponse

@typing.final
class ListDocumentsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    page_size: builtins.int
    """Number of documents to return per page"""
    page_token: builtins.str
    """Token for pagination"""
    def __init__(
        self,
        *,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token"]) -> None: ...

Global___ListDocumentsRequest: typing_extensions.TypeAlias = ListDocumentsRequest

@typing.final
class ListDocumentsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCUMENTS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """Token for the next page"""
    @property
    def documents(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___DocumentInfo]:
        """List of document information"""

    def __init__(
        self,
        *,
        documents: collections.abc.Iterable[Global___DocumentInfo] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["documents", b"documents", "next_page_token", b"next_page_token"]) -> None: ...

Global___ListDocumentsResponse: typing_extensions.TypeAlias = ListDocumentsResponse

@typing.final
class DocumentInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCUMENT_ID_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    UPLOAD_TIMESTAMP_FIELD_NUMBER: builtins.int
    CHUNKS_COUNT_FIELD_NUMBER: builtins.int
    document_id: builtins.str
    """Unique identifier for the document"""
    filename: builtins.str
    """Name of the document"""
    upload_timestamp: builtins.int
    """Upload timestamp"""
    chunks_count: builtins.int
    """Number of chunks in the document"""
    def __init__(
        self,
        *,
        document_id: builtins.str = ...,
        filename: builtins.str = ...,
        upload_timestamp: builtins.int = ...,
        chunks_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chunks_count", b"chunks_count", "document_id", b"document_id", "filename", b"filename", "upload_timestamp", b"upload_timestamp"]) -> None: ...

Global___DocumentInfo: typing_extensions.TypeAlias = DocumentInfo
