# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import grpc.experimental

from . import rag_service_pb2 as rag__service__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in rag_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RagServiceStub(object):
    """--------------------------------------------------------
    RAG Service Definition
    --------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
            "/rag.RagService/Chat",
            request_serializer=rag__service__pb2.ChatRequest.SerializeToString,
            response_deserializer=rag__service__pb2.ChatResponse.FromString,
            _registered_method=True,
        )
        self.UploadDocument = channel.unary_unary(
            "/rag.RagService/UploadDocument",
            request_serializer=rag__service__pb2.UploadRequest.SerializeToString,
            response_deserializer=rag__service__pb2.UploadResponse.FromString,
            _registered_method=True,
        )


class RagServiceServicer(object):
    """--------------------------------------------------------
    RAG Service Definition
    --------------------------------------------------------
    """

    def Chat(self, request, context):
        """/ Chat is an RPC that processes a user's query and returns a response.
        / It takes a ChatRequest containing the query, session ID, and configuration,
        / and returns a ChatResponse with the generated answer and source documents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UploadDocument(self, request, context):
        """/ UploadDocument is an RPC that handles document uploads.
        / It takes an UploadRequest with file details and content,
        / and returns an UploadResponse indicating the status of the upload.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Chat": grpc.unary_stream_rpc_method_handler(
            servicer.Chat,
            request_deserializer=rag__service__pb2.ChatRequest.FromString,
            response_serializer=rag__service__pb2.ChatResponse.SerializeToString,
        ),
        "UploadDocument": grpc.unary_unary_rpc_method_handler(
            servicer.UploadDocument,
            request_deserializer=rag__service__pb2.UploadRequest.FromString,
            response_serializer=rag__service__pb2.UploadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("rag.RagService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rag.RagService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RagService(object):
    """--------------------------------------------------------
    RAG Service Definition
    --------------------------------------------------------
    """

    @staticmethod
    def Chat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/rag.RagService/Chat",
            rag__service__pb2.ChatRequest.SerializeToString,
            rag__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UploadDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rag.RagService/UploadDocument",
            rag__service__pb2.UploadRequest.SerializeToString,
            rag__service__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
