"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import rag_service_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_ChatServiceChatType = typing_extensions.TypeVar(
    '_ChatServiceChatType',
    grpc.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
    grpc.aio.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
    default=grpc.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
)

class ChatServiceStub(typing.Generic[_ChatServiceChatType]):
    """--------------------------------------------------------
    Chat Service Definition
    --------------------------------------------------------
    """

    @typing.overload
    def __init__(self: ChatServiceStub[
        grpc.UnaryStreamMultiCallable[
            rag_service_pb2.ChatRequest,
            rag_service_pb2.ChatResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: ChatServiceStub[
        grpc.aio.UnaryStreamMultiCallable[
            rag_service_pb2.ChatRequest,
            rag_service_pb2.ChatResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Chat: _ChatServiceChatType
    """/ Chat is an RPC that processes a user's query and returns a response.
    / It takes a ChatRequest containing the query, session ID, and configuration,
    / and returns a ChatResponse with the generated answer and source documents.
    """

ChatServiceAsyncStub: typing_extensions.TypeAlias = ChatServiceStub[
    grpc.aio.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
]

class ChatServiceServicer(metaclass=abc.ABCMeta):
    """--------------------------------------------------------
    Chat Service Definition
    --------------------------------------------------------
    """

    @abc.abstractmethod
    def Chat(
        self,
        request: rag_service_pb2.ChatRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[rag_service_pb2.ChatResponse], collections.abc.AsyncIterator[rag_service_pb2.ChatResponse]]:
        """/ Chat is an RPC that processes a user's query and returns a response.
        / It takes a ChatRequest containing the query, session ID, and configuration,
        / and returns a ChatResponse with the generated answer and source documents.
        """

def add_ChatServiceServicer_to_server(servicer: ChatServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

_KnowledgeBaseServiceProcessDocumentType = typing_extensions.TypeVar(
    '_KnowledgeBaseServiceProcessDocumentType',
    grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.ProcessDocumentRequest,
        rag_service_pb2.ProcessDocumentResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.ProcessDocumentRequest,
        rag_service_pb2.ProcessDocumentResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.ProcessDocumentRequest,
        rag_service_pb2.ProcessDocumentResponse,
    ],
)

_KnowledgeBaseServiceDeleteDocumentType = typing_extensions.TypeVar(
    '_KnowledgeBaseServiceDeleteDocumentType',
    grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.DeleteDocumentRequest,
        rag_service_pb2.DeleteDocumentResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.DeleteDocumentRequest,
        rag_service_pb2.DeleteDocumentResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.DeleteDocumentRequest,
        rag_service_pb2.DeleteDocumentResponse,
    ],
)

class KnowledgeBaseServiceStub(typing.Generic[_KnowledgeBaseServiceProcessDocumentType, _KnowledgeBaseServiceDeleteDocumentType]):
    """--------------------------------------------------------
    Knowledge Base Service Definition
    --------------------------------------------------------
    """

    @typing.overload
    def __init__(self: KnowledgeBaseServiceStub[
        grpc.UnaryUnaryMultiCallable[
            rag_service_pb2.ProcessDocumentRequest,
            rag_service_pb2.ProcessDocumentResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            rag_service_pb2.DeleteDocumentRequest,
            rag_service_pb2.DeleteDocumentResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: KnowledgeBaseServiceStub[
        grpc.aio.UnaryUnaryMultiCallable[
            rag_service_pb2.ProcessDocumentRequest,
            rag_service_pb2.ProcessDocumentResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            rag_service_pb2.DeleteDocumentRequest,
            rag_service_pb2.DeleteDocumentResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    ProcessDocument: _KnowledgeBaseServiceProcessDocumentType
    """/ ProcessDocument is an RPC that processes a document that was already saved by Go.
    / Go provides the document_id, file_path, and metadata. Python processes and indexes it.
    """

    DeleteDocument: _KnowledgeBaseServiceDeleteDocumentType
    """/ DeleteDocument is an RPC that deletes a specified document from the vector store.
    / It takes a DeleteDocumentRequest and returns a DeleteDocumentResponse.
    """

KnowledgeBaseServiceAsyncStub: typing_extensions.TypeAlias = KnowledgeBaseServiceStub[
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.ProcessDocumentRequest,
        rag_service_pb2.ProcessDocumentResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.DeleteDocumentRequest,
        rag_service_pb2.DeleteDocumentResponse,
    ],
]

class KnowledgeBaseServiceServicer(metaclass=abc.ABCMeta):
    """--------------------------------------------------------
    Knowledge Base Service Definition
    --------------------------------------------------------
    """

    @abc.abstractmethod
    def ProcessDocument(
        self,
        request: rag_service_pb2.ProcessDocumentRequest,
        context: _ServicerContext,
    ) -> typing.Union[rag_service_pb2.ProcessDocumentResponse, collections.abc.Awaitable[rag_service_pb2.ProcessDocumentResponse]]:
        """/ ProcessDocument is an RPC that processes a document that was already saved by Go.
        / Go provides the document_id, file_path, and metadata. Python processes and indexes it.
        """

    @abc.abstractmethod
    def DeleteDocument(
        self,
        request: rag_service_pb2.DeleteDocumentRequest,
        context: _ServicerContext,
    ) -> typing.Union[rag_service_pb2.DeleteDocumentResponse, collections.abc.Awaitable[rag_service_pb2.DeleteDocumentResponse]]:
        """/ DeleteDocument is an RPC that deletes a specified document from the vector store.
        / It takes a DeleteDocumentRequest and returns a DeleteDocumentResponse.
        """

def add_KnowledgeBaseServiceServicer_to_server(servicer: KnowledgeBaseServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
