"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import rag_service_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_ChatServiceChatType = typing_extensions.TypeVar(
    '_ChatServiceChatType',
    grpc.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
    grpc.aio.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
    default=grpc.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
)

class ChatServiceStub(typing.Generic[_ChatServiceChatType]):
    """--------------------------------------------------------
    Chat Service Definition
    --------------------------------------------------------
    """

    @typing.overload
    def __init__(self: ChatServiceStub[
        grpc.UnaryStreamMultiCallable[
            rag_service_pb2.ChatRequest,
            rag_service_pb2.ChatResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: ChatServiceStub[
        grpc.aio.UnaryStreamMultiCallable[
            rag_service_pb2.ChatRequest,
            rag_service_pb2.ChatResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Chat: _ChatServiceChatType
    """/ Chat is an RPC that processes a user's query and returns a response.
    / It takes a ChatRequest containing the query, session ID, and configuration,
    / and returns a ChatResponse with the generated answer and source documents.
    """

ChatServiceAsyncStub: typing_extensions.TypeAlias = ChatServiceStub[
    grpc.aio.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
]

class ChatServiceServicer(metaclass=abc.ABCMeta):
    """--------------------------------------------------------
    Chat Service Definition
    --------------------------------------------------------
    """

    @abc.abstractmethod
    def Chat(
        self,
        request: rag_service_pb2.ChatRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[rag_service_pb2.ChatResponse], collections.abc.AsyncIterator[rag_service_pb2.ChatResponse]]:
        """/ Chat is an RPC that processes a user's query and returns a response.
        / It takes a ChatRequest containing the query, session ID, and configuration,
        / and returns a ChatResponse with the generated answer and source documents.
        """

def add_ChatServiceServicer_to_server(servicer: ChatServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

_KnowledgeBaseServiceUploadDocumentType = typing_extensions.TypeVar(
    '_KnowledgeBaseServiceUploadDocumentType',
    grpc.StreamUnaryMultiCallable[
        rag_service_pb2.UploadRequest,
        rag_service_pb2.UploadResponse,
    ],
    grpc.aio.StreamUnaryMultiCallable[
        rag_service_pb2.UploadRequest,
        rag_service_pb2.UploadResponse,
    ],
    default=grpc.StreamUnaryMultiCallable[
        rag_service_pb2.UploadRequest,
        rag_service_pb2.UploadResponse,
    ],
)

_KnowledgeBaseServiceDeleteDocumentType = typing_extensions.TypeVar(
    '_KnowledgeBaseServiceDeleteDocumentType',
    grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.DeleteDocumentRequest,
        rag_service_pb2.DeleteDocumentResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.DeleteDocumentRequest,
        rag_service_pb2.DeleteDocumentResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.DeleteDocumentRequest,
        rag_service_pb2.DeleteDocumentResponse,
    ],
)

_KnowledgeBaseServiceListDocumentsType = typing_extensions.TypeVar(
    '_KnowledgeBaseServiceListDocumentsType',
    grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.ListDocumentsRequest,
        rag_service_pb2.ListDocumentsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.ListDocumentsRequest,
        rag_service_pb2.ListDocumentsResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.ListDocumentsRequest,
        rag_service_pb2.ListDocumentsResponse,
    ],
)

class KnowledgeBaseServiceStub(typing.Generic[_KnowledgeBaseServiceUploadDocumentType, _KnowledgeBaseServiceDeleteDocumentType, _KnowledgeBaseServiceListDocumentsType]):
    """--------------------------------------------------------
    Knowledge Base Service Definition
    --------------------------------------------------------
    """

    @typing.overload
    def __init__(self: KnowledgeBaseServiceStub[
        grpc.StreamUnaryMultiCallable[
            rag_service_pb2.UploadRequest,
            rag_service_pb2.UploadResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            rag_service_pb2.DeleteDocumentRequest,
            rag_service_pb2.DeleteDocumentResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            rag_service_pb2.ListDocumentsRequest,
            rag_service_pb2.ListDocumentsResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: KnowledgeBaseServiceStub[
        grpc.aio.StreamUnaryMultiCallable[
            rag_service_pb2.UploadRequest,
            rag_service_pb2.UploadResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            rag_service_pb2.DeleteDocumentRequest,
            rag_service_pb2.DeleteDocumentResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            rag_service_pb2.ListDocumentsRequest,
            rag_service_pb2.ListDocumentsResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    UploadDocument: _KnowledgeBaseServiceUploadDocumentType
    """/ UploadDocument is an RPC that uploads a document in chunks.
    / It takes a stream of UploadRequest messages and returns an UploadResponse.
    """

    DeleteDocument: _KnowledgeBaseServiceDeleteDocumentType
    """/ DeleteDocument is an RPC that deletes a specified document.
    / It takes a DeleteDocumentRequest and returns a DeleteDocumentResponse.
    """

    ListDocuments: _KnowledgeBaseServiceListDocumentsType
    """/ ListDocuments is an RPC that lists all documents in the knowledge base.
    / It takes a ListDocumentsRequest and returns a ListDocumentsResponse.
    """

KnowledgeBaseServiceAsyncStub: typing_extensions.TypeAlias = KnowledgeBaseServiceStub[
    grpc.aio.StreamUnaryMultiCallable[
        rag_service_pb2.UploadRequest,
        rag_service_pb2.UploadResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.DeleteDocumentRequest,
        rag_service_pb2.DeleteDocumentResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.ListDocumentsRequest,
        rag_service_pb2.ListDocumentsResponse,
    ],
]

class KnowledgeBaseServiceServicer(metaclass=abc.ABCMeta):
    """--------------------------------------------------------
    Knowledge Base Service Definition
    --------------------------------------------------------
    """

    @abc.abstractmethod
    def UploadDocument(
        self,
        request_iterator: _MaybeAsyncIterator[rag_service_pb2.UploadRequest],
        context: _ServicerContext,
    ) -> typing.Union[rag_service_pb2.UploadResponse, collections.abc.Awaitable[rag_service_pb2.UploadResponse]]:
        """/ UploadDocument is an RPC that uploads a document in chunks.
        / It takes a stream of UploadRequest messages and returns an UploadResponse.
        """

    @abc.abstractmethod
    def DeleteDocument(
        self,
        request: rag_service_pb2.DeleteDocumentRequest,
        context: _ServicerContext,
    ) -> typing.Union[rag_service_pb2.DeleteDocumentResponse, collections.abc.Awaitable[rag_service_pb2.DeleteDocumentResponse]]:
        """/ DeleteDocument is an RPC that deletes a specified document.
        / It takes a DeleteDocumentRequest and returns a DeleteDocumentResponse.
        """

    @abc.abstractmethod
    def ListDocuments(
        self,
        request: rag_service_pb2.ListDocumentsRequest,
        context: _ServicerContext,
    ) -> typing.Union[rag_service_pb2.ListDocumentsResponse, collections.abc.Awaitable[rag_service_pb2.ListDocumentsResponse]]:
        """/ ListDocuments is an RPC that lists all documents in the knowledge base.
        / It takes a ListDocumentsRequest and returns a ListDocumentsResponse.
        """

def add_KnowledgeBaseServiceServicer_to_server(servicer: KnowledgeBaseServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
