"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import rag_service_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_RagServiceChatType = typing_extensions.TypeVar(
    '_RagServiceChatType',
    grpc.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
    grpc.aio.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
    default=grpc.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
)

_RagServiceUploadDocumentType = typing_extensions.TypeVar(
    '_RagServiceUploadDocumentType',
    grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.UploadRequest,
        rag_service_pb2.UploadResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.UploadRequest,
        rag_service_pb2.UploadResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        rag_service_pb2.UploadRequest,
        rag_service_pb2.UploadResponse,
    ],
)

class RagServiceStub(typing.Generic[_RagServiceChatType, _RagServiceUploadDocumentType]):
    """--------------------------------------------------------
    RAG Service Definition
    --------------------------------------------------------
    """

    @typing.overload
    def __init__(self: RagServiceStub[
        grpc.UnaryStreamMultiCallable[
            rag_service_pb2.ChatRequest,
            rag_service_pb2.ChatResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            rag_service_pb2.UploadRequest,
            rag_service_pb2.UploadResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: RagServiceStub[
        grpc.aio.UnaryStreamMultiCallable[
            rag_service_pb2.ChatRequest,
            rag_service_pb2.ChatResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            rag_service_pb2.UploadRequest,
            rag_service_pb2.UploadResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Chat: _RagServiceChatType
    """/ Chat is an RPC that processes a user's query and returns a response.
    / It takes a ChatRequest containing the query, session ID, and configuration,
    / and returns a ChatResponse with the generated answer and source documents.
    """

    UploadDocument: _RagServiceUploadDocumentType
    """/ UploadDocument is an RPC that handles document uploads.
    / It takes an UploadRequest with file details and content,
    / and returns an UploadResponse indicating the status of the upload.
    """

RagServiceAsyncStub: typing_extensions.TypeAlias = RagServiceStub[
    grpc.aio.UnaryStreamMultiCallable[
        rag_service_pb2.ChatRequest,
        rag_service_pb2.ChatResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        rag_service_pb2.UploadRequest,
        rag_service_pb2.UploadResponse,
    ],
]

class RagServiceServicer(metaclass=abc.ABCMeta):
    """--------------------------------------------------------
    RAG Service Definition
    --------------------------------------------------------
    """

    @abc.abstractmethod
    def Chat(
        self,
        request: rag_service_pb2.ChatRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[rag_service_pb2.ChatResponse], collections.abc.AsyncIterator[rag_service_pb2.ChatResponse]]:
        """/ Chat is an RPC that processes a user's query and returns a response.
        / It takes a ChatRequest containing the query, session ID, and configuration,
        / and returns a ChatResponse with the generated answer and source documents.
        """

    @abc.abstractmethod
    def UploadDocument(
        self,
        request: rag_service_pb2.UploadRequest,
        context: _ServicerContext,
    ) -> typing.Union[rag_service_pb2.UploadResponse, collections.abc.Awaitable[rag_service_pb2.UploadResponse]]:
        """/ UploadDocument is an RPC that handles document uploads.
        / It takes an UploadRequest with file details and content,
        / and returns an UploadResponse indicating the status of the upload.
        """

def add_RagServiceServicer_to_server(servicer: RagServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
